const fs=require('node:fs');const path=require('node:path');const {pages}=require('./content.cjs');
const out=path.join(__dirname,'dist');const origin='https://almarack.com';const production=process.argv.includes('--production');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const href=p=>'/'+p.slug+'/';const group=name=>pages.filter(p=>p.group===name);const links=ps=>ps.map(p=>`<a href="${href(p)}">${esc(p.label)}</a>`).join('');
const wa='https://wa.me/34660823482?text='+encodeURIComponent('Hola Almar-Rack, me gustaría consultar un servicio para mi almacén.');
const header=`<header class="header"><a class="brand" href="/" aria-label="Almar-Rack, inicio"><span class="brand-logo" aria-hidden="true"><img src="/assets/marca-almar.webp" alt=""></span><span>ALMAR<span class="brand-dash">—</span>RACK<small>SEGURIDAD EN CADA ESTRUCTURA</small></span></a><nav class="site-nav" aria-label="Navegación principal"><details class="nav-group"><summary>Servicios</summary><div class="nav-panel">${links(group('Servicios'))}</div></details><details class="nav-group"><summary>Recursos</summary><div class="nav-panel">${links(group('Recursos'))}</div></details><a href="/proyectos/">Proyectos</a><a href="/cobertura-nacional/">Cobertura</a><a href="/sobre-almarack/">Empresa</a><a class="nav-contact" href="/contacto/">Hablemos ↗</a></nav><details class="mobile-navigation"><summary>Menú</summary><nav aria-label="Navegación móvil"><a href="/">Inicio</a><strong>Servicios</strong>${links(group('Servicios'))}<strong>Recursos</strong>${links(group('Recursos'))}<strong>Almar-Rack</strong>${links(group('Empresa'))}${links(group('Cobertura'))}</nav></details></header>`;
const footer=`<footer class="site-footer"><div class="footer-top"><div><a class="footer-brand" href="/">ALMAR—RACK</a><p>Seguridad en cada estructura.<br>Montaje, inspección y mantenimiento<br>desde Guadalajara a toda España.</p><a href="tel:+34660823482">+34 660 82 34 82</a><a href="mailto:info@almarack.com">info@almarack.com</a></div><div><h2>Servicios</h2>${links(group('Servicios'))}</div><div><h2>Conocimiento</h2>${links(group('Recursos'))}<h2>La empresa</h2>${links(group('Empresa').filter(p=>p.slug!=='contacto'))}</div><div><h2>Dónde estamos</h2>${links(group('Cobertura'))}<p>C/ Alvarfáñez de Minaya 1B<br>19001 Guadalajara · España</p><a href="/contacto/">Contacto y horarios</a></div></div><div class="footer-bottom"><span>© 2026 Almar-Rack</span><nav aria-label="Información legal">${links(group('Legal'))}<a href="/mapa-del-sitio/">Mapa del sitio</a></nav><span>Portada: escenas recreadas.</span></div></footer>`;
const org={'@type':'LocalBusiness','@id':origin+'/#organization',name:'Almar-Rack',alternateName:['Almarack','ALMAR-RACK'],url:origin+'/',telephone:'+34660823482',email:'info@almarack.com',address:{'@type':'PostalAddress',streetAddress:'C/ Alvarfáñez de Minaya 1B',addressLocality:'Guadalajara',postalCode:'19001',addressCountry:'ES'},areaServed:{'@type':'Country',name:'España'}};
function metadata(p){const url=origin+(p.slug?href(p):'/');const schema={'@context':'https://schema.org','@graph':[org,{'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:'Almar-Rack',inLanguage:'es-ES',publisher:{'@id':org['@id']}},{'@type':'WebPage','@id':url+'#webpage',url,name:p.label,description:p.intro,inLanguage:'es-ES',isPartOf:{'@id':origin+'/#website'},about:{'@id':org['@id']}},...(p.slug?[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Inicio',item:origin+'/'},{'@type':'ListItem',position:2,name:p.label,item:url}]}]:[]),...(p.group==='Servicios'?[{'@type':'Service',name:p.label,description:p.intro,url,provider:{'@id':org['@id']},areaServed:{'@type':'Country',name:'España'}}]:[])]};return `<title>${esc(p.label)} | Almar-Rack</title><meta name="description" content="${esc(p.intro)}"><meta name="robots" content="${production?'index,follow,max-image-preview:large':'noindex,follow'}"><link rel="canonical" href="${url}"><meta property="og:title" content="${esc(p.label)} | Almar-Rack"><meta property="og:description" content="${esc(p.intro)}"><meta property="og:type" content="website"><meta property="og:locale" content="es_ES"><meta property="og:url" content="${url}"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`;}
const favicon=`<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%23081419'/%3E%3Cpath d='M8 25V7h4v18m8 0V7h4v18' stroke='%23ff814b' stroke-width='3'/%3E%3Cpath d='M10 11h12M10 21h12' stroke='white' stroke-width='3'/%3E%3C/svg%3E">`;
const css=`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap"><link rel="stylesheet" href="/styles.css?v=20260914-3"><link rel="stylesheet" href="/site.css?v=20260914-3">`;
const contact=`<section class="closing-cta"><div><span class="section-label">HABLEMOS DE TU INSTALACIÓN</span><h2>El siguiente paso<br>empieza <em>contigo.</em></h2></div><div><p>Fotos, ubicación y lo que necesitas.<br>Nos ocupamos de estudiar cómo ayudarte.</p><a class="button orange" href="${wa}" target="_blank" rel="noopener">Consultar por WhatsApp ↗</a><a class="closing-phone" href="tel:+34660823482">+34 660 82 34 82</a><a href="mailto:info@almarack.com">info@almarack.com</a></div></section>`;
const sourceLinks=`<aside class="technical-note"><h2>Referencias y alcance</h2><p>Contenido divulgativo. Consulta el caso concreto con personal competente y con tu servicio de prevención.</p><a href="https://www.boe.es/buscar/act.php?id=BOE-A-1997-17824" target="_blank" rel="noopener">RD 1215/1997 · BOE ↗</a><a href="https://www.insst.es/documentacion/colecciones-tecnicas/ntp-notas-tecnicas-de-prevencion/24-serie-ntp-numeros-821-a-855-ano-2009/nota-tecnica-de-prevencion-ntp-852" target="_blank" rel="noopener">NTP 852 · INSST ↗</a><a href="https://www.insst.es/documentacion/herramientas-de-prl/calculadores/estanterias-metalicas-condiciones-de-seguridad-2022" target="_blank" rel="noopener">Herramienta de revisión · INSST ↗</a></aside>`;
const faqHtml=p=>p.faq.length?`<section class="page-faq" id="preguntas"><div class="section-label">RESPUESTAS CLARAS</div><h2>Lo que necesitas saber.</h2>${p.faq.map(([q,a,slug])=>`<details><summary>${esc(q)}</summary><div><p>${esc(a)}</p>${slug?`<a href="/${slug}/">Más sobre este servicio ↗</a>`:''}</div></details>`).join('')}</section>`:'';
const cases=[['pasillo-alicante.webp','Protección de estanterías','Alicante · Protecciones de puntal y cabeceras'],['proteccion-robot.webp','Protección de procesos','Planta de envases · Barreras junto a maquinaria'],['detalle-proteccion.webp','Muelles y accesos','Quer · Protección de puertas y zonas de paso'],['entreplanta.webp','Espacio en altura','Estructura y elementos de protección']];
const gallery=`<div class="case-gallery">${cases.map(([im,t,c])=>`<figure><img src="/assets/${im}" alt="${esc(c)}" loading="lazy" width="1200" height="1000"><figcaption><h2>${t}</h2><p>${c}</p></figcaption></figure>`).join('')}</div>`;
function render(p){const items=p.sections.map((x,i)=>`<section class="editorial-section" id="apartado-${i+1}"><span class="section-index">${String(i+1).padStart(2,'0')}</span><div><h2>${esc(x.title)}</h2><p>${esc(x.text)}</p>${x.items.length?`<ul>${x.items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}</div></section>`).join('');return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${metadata(p)}${favicon}${css}</head><body class="inner-page"><a class="skip" href="#contenido">Saltar al contenido</a>${header}<main id="contenido"><section class="page-hero ${p.image?'has-photo':''}"><div><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/">Inicio</a><span>/</span><span>${p.group}</span></nav><div class="section-label">ALMAR-RACK / ${p.group.toUpperCase()}</div><h1>${esc(p.label)}</h1><p class="page-intro">${esc(p.intro)}</p>${p.group!=='Legal'?`<a class="button orange" href="${wa}" target="_blank" rel="noopener">Habla con un técnico ↗</a>`:''}</div>${p.image?`<figure><img src="/assets/${p.image}" alt="${esc(p.slug==='sobre-almarack'?'Retrato corporativo de Diego Núñez':p.label+' · Material de Almar-Rack')}" width="1000" height="1200"></figure>`:''}</section><div class="page-layout"><aside class="page-index"><span class="section-label">EN ESTA PÁGINA</span>${p.sections.map((x,i)=>`<a href="#apartado-${i+1}">${esc(x.title)}</a>`).join('')}${p.faq.length?'<a href="#preguntas">Preguntas frecuentes</a>':''}<a class="index-contact" href="/contacto/">Consultar mi instalación ↗</a></aside><article class="editorial">${p.slug==='checklist-revision-estanterias'?'<button class="button print-button" type="button" data-print>Imprimir checklist / guardar PDF</button><div class="print-fields">Centro: __________________ Fecha: __________ Responsable: __________________</div>':''}${p.slug==='proyectos'?gallery:''}${items}${faqHtml(p)}${['normativa-estanterias-industriales','guia-prses-seguridad-almacen','inspecciones-une-en-15635','checklist-revision-estanterias'].includes(p.slug)?sourceLinks:''}${p.slug==='contacto'?'<p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Almar-Rack%2C%20Guadalajara" target="_blank" rel="noopener">Ver ubicación en Google Maps ↗</a></p>':''}</article></div>${p.group!=='Legal'?`<section class="related"><span class="section-label">SIGUE EXPLORANDO</span><div>${links((p.group==='Servicios'?group('Servicios'):group('Recursos')).filter(x=>x.slug!==p.slug))}</div></section>${contact}`:''}</main>${footer}<script src="/site.js?v=20260914-3" defer></script></body></html>`;}
for(const p of pages){fs.mkdirSync(path.join(out,p.slug),{recursive:true});fs.writeFileSync(path.join(out,p.slug,'index.html'),render(p));}
const cards=`<section class="expanded-services services" id="soluciones"><div class="services-heading"><div><div class="section-label">SOLUCIONES PARA TU ALMACÉN</div><h2>Todo el ciclo de vida.<br><em>Un mismo compromiso.</em></h2></div><p>Inspección, reparación, protección<br>y montaje de estanterías industriales.</p></div><div class="service-cards">${group('Servicios').map((p,i)=>`<a href="${href(p)}"><span>${String(i+1).padStart(2,'0')} / ${i<4?'SEGURIDAD':'INSTALACIÓN Y CUIDADO'}</span><h3>${esc(p.label)}</h3><p>${esc(p.intro)}</p><b>Explorar servicio ↗</b></a>`).join('')}</div></section>`;
const homeExtras=`${cards}<section class="knowledge"><div><span class="section-label">CONOCIMIENTO QUE AYUDA</span><h2>Decisiones claras.<br>Almacenes <em>mejor cuidados.</em></h2><p>Guías para responsables de almacén, operaciones y prevención. Información práctica que acompaña al trabajo técnico.</p></div><div class="knowledge-links">${links(group('Recursos'))}</div></section><section class="coverage-section"><div><span class="section-label">BASE EN GUADALAJARA / COBERTURA NACIONAL</span><h2>Cerca de tu equipo.<br>Donde <em>lo necesites.</em></h2><p>Atendemos Madrid y el Corredor del Henares, y planificamos intervenciones en el resto de España. Coordinamos visitas, desplazamientos y alcance antes de empezar.</p></div><div class="coverage-links">${links(group('Cobertura'))}<a class="button orange" href="/contacto/">Consultar disponibilidad ↗</a></div></section><section class="working-process"><span class="section-label">ASÍ TRABAJAMOS</span><h2>Del primer detalle<br>a una actuación documentada.</h2><div>${[['Escuchamos','Ubicación, fotografías, planos y necesidades de tu almacén.'],['Evaluamos','Revisión de la instalación y alcance de la solución.'],['Planificamos','Presupuesto, zonas de trabajo y calendario acordados.'],['Comprobamos','Resultado de la intervención y documentación para su seguimiento.']].map(([h,p],i)=>`<div><span>0${i+1}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div><p class="scene-disclosure">La historia de la portada es una recreación visual. Una reparación real exige evaluación, método adecuado y comprobaciones; la pegatina no sustituye el informe técnico.</p></section>`;
let home=fs.readFileSync(path.join(out,'index.html'),'utf8');
home=home.replace(/<header\b[\s\S]*?<\/header>/,header).replace(/<footer\b[\s\S]*?<\/footer>/,footer);
home=home.replace(/<!-- EXPANDED-START -->[\s\S]*?<!-- EXPANDED-END -->/,'');
home=home.replace(/<section class="services" id="soluciones">[\s\S]*?(?=<section class="people">)/,'');
home=home.replace('<section class="people">',`<!-- EXPANDED-START -->${homeExtras}<!-- EXPANDED-END --><section class="people">`);
home=home.replace(/<title>[\s\S]*?<\/title>/,'').replace(/<meta name="description"[^>]*>/,'').replace(/<!-- SEO-START -->[\s\S]*?<!-- SEO-END -->/,'');
home=home.replace('</head>',`<!-- SEO-START -->${metadata({label:'Inspección, reparación y montaje de estanterías industriales',intro:'Almar-Rack: inspección UNE-EN 15635, reparación, protecciones MPM y montaje. Base en Guadalajara y servicio en Madrid y toda España.'})}<link rel="stylesheet" href="/site.css?v=20260914-3"><!-- SEO-END --></head>`).replace('styles.css?v=20260914-2','styles.css?v=20260914-3');
home=home.replace(/<script src="\/site.js[^>]*><\/script>/,'').replace('</body>','<script src="/site.js?v=20260914-3" defer></script></body>');
fs.writeFileSync(path.join(out,'index.html'),home);
const map={slug:'mapa-del-sitio',label:'Mapa del sitio',group:'Recursos',intro:'Servicios, recursos y páginas de Almar-Rack.',image:'',faq:[],sections:[]};
const mapHtml=render(map).replace('<article class="editorial">','<article class="editorial"><div class="site-directory">'+['Servicios','Recursos','Empresa','Cobertura','Legal'].map(g=>`<section><h2>${g}</h2>${links(group(g))}</section>`).join('')+'</div>');fs.mkdirSync(path.join(out,map.slug),{recursive:true});fs.writeFileSync(path.join(out,map.slug,'index.html'),mapHtml);
const paths=['/',...pages.map(href),'/mapa-del-sitio/'];fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+paths.map(u=>`<url><loc>${origin+u}</loc></url>`).join('')+'</urlset>');
fs.writeFileSync(path.join(out,'robots.txt'),production?`User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n# Vista de revisión. Activar indexación solo al publicar el dominio definitivo.\n');
const llms=`# Almar-Rack\n\n> Servicios de montaje, inspección, reparación, protección y mantenimiento de estanterías industriales.\n\nWeb oficial: ${origin}/\nContacto: info@almarack.com · +34 660 82 34 82\nBase: Guadalajara, España. Servicio en Madrid, Corredor del Henares y trabajos planificados en España.\n\n## Servicios y recursos\n${pages.filter(p=>p.group!=='Legal').map(p=>`- [${p.label}](${origin+href(p)}): ${p.intro}`).join('\n')}\n\n## Alcance\nInformación comercial y divulgativa. Una instalación requiere evaluación técnica concreta. Los plazos están sujetos a confirmación. Las escenas de portada son recreadas. No se publican valoraciones, certificaciones ni rankings no acreditados.\n\n- [Contenido completo](${origin}/llms-full.txt)\n`;
fs.writeFileSync(path.join(out,'llms.txt'),llms);fs.writeFileSync(path.join(out,'llms-full.txt'),llms+'\n'+pages.filter(p=>p.group!=='Legal').map(p=>`# ${p.label}\nURL: ${origin+href(p)}\n${p.intro}\n\n${p.sections.map(x=>`## ${x.title}\n${x.text}\n${x.items.map(t=>'- '+t).join('\n')}`).join('\n\n')}\n${p.faq.map(([q,a])=>`## ${q}\n${a}`).join('\n\n')}`).join('\n\n'));
fs.writeFileSync(path.join(out,'_redirects'),'/privacy-policy/ /politica-de-privacidad/ 301\n/politica-de-cookies-ue/ /politica-de-cookies/ 301\n/sitemap_index.xml /sitemap.xml 301\n');
fs.writeFileSync(path.join(out,'404.html'),`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Página no encontrada | Almar-Rack</title><meta name="robots" content="noindex">${css}</head><body class="inner-page">${header}<main class="page-hero"><div><span class="section-label">404</span><h1>No encontramos esa página.</h1><p>Consulta nuestros servicios o vuelve al inicio.</p><a class="button orange" href="/">Volver al inicio</a></div></main>${footer}</body></html>`);
console.log(JSON.stringify({pages:paths.length,mode:production?'production':'private-preview',sitemap:paths.length}));
